//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellentTaste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestelling
    {
        public int bestellingId { get; set; }
        public int reserveringId { get; set; }
        public string consumptieItemCode { get; set; }
        public int aantal { get; set; }
        public Nullable<System.DateTime> dateTimeBereidingConsumptie { get; set; }
        public decimal prijs { get; set; }
        public Nullable<decimal> totaal { get; set; }
    
        public virtual ConsumptieItem ConsumptieItem { get; set; }
        public virtual Reservering Reservering { get; set; }
    }
}
