//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcellentTaste.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservering
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservering()
        {
            this.Bestelling = new HashSet<Bestelling>();
        }
    
        public int reserveringId { get; set; }
        public int klantId { get; set; }
        public System.DateTime datum { get; set; }
        public System.TimeSpan tijd { get; set; }
        public int tafel { get; set; }
        public int aantalPersonen { get; set; }
        public Nullable<int> status { get; set; }
        public System.DateTime datumToegevoegd { get; set; }
        public Nullable<System.DateTime> bonDatum { get; set; }
        public string betalingswijze { get; set; }
        public Nullable<decimal> bonTotaal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bestelling> Bestelling { get; set; }
        public virtual Klant Klant { get; set; }
    }
}
